### ISSUE TITLE
Duda en traducción element-wise

### ISSUE THREAD

**Issue by orchid00** [carpentries/r-novice-gapminder#16]

**Comment by rzayas** [comment]
Tengo dudas de cómo se debe traducir element-wise. El contexto tiene que ver con operaciones entre vectores y números o elementos.

**Comment by rzayas** [comment]
creo que cerré el comentario por error.

**Comment by orchid00** [comment]
Podrías poner la oración completa por fa

**Comment by orchid00** [comment]
Me parece que significa por cada elemento

**Comment by rzayas** [comment]
"Most functions also operate element-wise on vectors:"

"Vectorized operations work element-wise on matrices:"

"> ## Tip: element-wise vs. matrix multiplication"

"> Very important: the operator `*` gives you element-wise multiplication!"

**Comment by agbeltran** [comment]
Hola! Sí, quiere decir que la función opera "elemento por elemento" (definición aquí: https://en.wiktionary.org/wiki/elementwise).

En este [documento en español](http://www.ugr.es/~jchica/Pagina2/GUIME/R/Primeros%20pasos.pdf) veo que le llaman "componente por componente", pero me parece mejor traducir "la función opera elemento por elemento".

Qué te parece?

**Comment by rzayas** [comment]
Me parece bien. De acuerdo. Entonces las frases quedarían así:

"La mayoría de las funciones también operan elemento por elemento en los vectores:"

"Operaciones vectorizadas trabajan elemento por elemento en matrices:"

"> ## Tip: multiplicación elemento por elemento vs. multiplicación de matriz"

"Muy importante: el operador`*` te da una multiplicación de elemento por elemento"

Gracias Ale.

**Comment by orchid00** [comment]
biensisimo! gracias @rzayas @agbeltran
