### ISSUE TITLE
Episode 06: Se tradujo el tipo de datos logical

### ISSUE THREAD

**Issue by jmbarrios** [carpentries/r-novice-gapminder#20]
Después de hacer la traducción de la lección 06 se decidió no traducir el término **logical** 
cuando se refiere a tipo de dato. En la lección entregada esta traducción ya había sido hecha.

**Comment by orchid00** [comment]
Gracias Juan!

**Comment by jmbarrios** [comment]
@orchid00  puedes abrir este **issue** otra vez, y asignarmelo?

**Comment by jmbarrios** [comment]
Resuelto en #21
